name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# 把这段删掉或改为 cancel-in-progress: false
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build           # 你的构建命令
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./public                      # 输出目录

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
